-- CREATING NEW SCHEMAS IN dwh_helpdesk
IF SCHEMA_ID('bronze') IS NOT NULL
DROP SCHEMA bronze
GO

CREATE SCHEMA bronze;
GO

IF SCHEMA_ID('silver') IS NOT NULL
DROP SCHEMA bronze
GO
CREATE SCHEMA silver;
GO

IF SCHEMA_ID('gold') IS NOT NULL
DROP SCHEMA bronze
GO
CREATE SCHEMA gold;
GO

-- TO CHECK IF THE SCHEMAS WERE CREATED OR NOT 
SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME IN ('bronze','silver','gold')
